#!/bin/sh

# This script recursively find and delete each file in the given search
# path with a modification time older than 30 days. Then recursively find
# and delete empty directories in the given search path.
#
# This script is intended to be used as a maintenance tool to clean
# temporary files older than 30 days.

# Warning: this script find and DELETE arbitrary files in the given search
# path without prompting. Use with caution.

echo "Cleaning old files in /Volumes/Public HD/com-public"

# Find and delete all:
#   - files older than 30 days ago
#   - empty directories
#   - .DS_Store files
#   - Thumbs.db files
find /Volumes/Public\ HD/com-public \( -type f -not -newermt '30 days ago' -delete \) -or \( -type d -empty -delete \) -or \( -name ".DS_Store" -delete \) -or \( -name "Thumbs.db" -delete \)
