#!/bin/sh

# This script recursively find and delete each file in the given search
# path with a access time older than 30 days. Then recursively find
# and delete empty directories in the given search path.
#
# This script is intended to be used as a maintenance tool to clean
# temporary files older than 30 days.

# WARNING: THIS SCRIPT FINDS AND DELETE ARBITRARY FILES IN THE GIVEN SEARCH
# PATH WITHOUT PROMPTING. USE WITH CAUTION!

search_path="tmp dir"
verbose="" #"-print"

# Swap the input field separator to deal with search path containing spaces
SAVEIFS=$IFS
IFS=$'\n'

echo ""
echo "# Cleaning old files in $search_path"

echo "  Removing files with access time older than 30 days ago"
find $search_path -type f -not -newerat '30 days ago' -delete $verbose

echo "  Removing Directoy Store and Thumbnail Cache"
find $search_path -name ".DS_Store" -delete $verbose
find $search_path -name "Thumbs.db" -delete $verbose

echo "  Removing empty folders"
find $search_path -type d -empty -delete $verbose

IFS=$SAVEIFS
